### ISSUE TITLE
`recipe.php` Structure

### ISSUE THREAD

**Issue by philsinatra** [vhs25/idm232-vhs25-MAMP#1]
I would not recommend putting the entire `<body>` contents within the loop:

https://github.com/vhs25/idm232-vhs25-MAMP/blob/292992512b71f563978245a9a545668a666197a5/recipe.php#L15-L17

Try moving your loop further into your `<body>` so you can see some of the structure of the page. If you have an error, currently nothing is rendering since the loop isn't executing, so you see a blank page. Start with this small adjustment and see if you can debug where the error is coming from. Work on this locally first, then upload your fixed `recipe.php` file to your remote server and double check your fix works there as well.

**Comment by vhs25** [comment]
I found it - I didn't realize I had included the $_GET(id) was a part of my first set of php code when I replaced it with an include. Thank you for your help!
